# Generated by Django 5.0.4 on 2024-05-01 22:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_studentgroups_subjects_alter_staffs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Завдання в роботі', 'verbose_name_plural': 'Завдання в роботі'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Нотатки', 'verbose_name_plural': 'Нотатки'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Справа на виконання', 'verbose_name_plural': 'Перелік справ'},
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='due',
            new_name='finishdate',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
        migrations.AddField(
            model_name='homework',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='homework',
            name='gradedescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subjects'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Пн', 'Понеділок'), ('Вт', 'Вівторок'), ('Ср', 'Середа'), ('Чт', 'Четвер'), ('Пт', 'Пятниця')], default='Пн', max_length=20)),
                ('class_num', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('comment', models.CharField(max_length=200)),
                ('teaching_assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.teachingassignments')),
            ],
            options={
                'verbose_name': 'Запис в розкладі занять',
                'verbose_name_plural': 'Розклад занять',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.studentgroups')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subjects')),
            ],
            options={
                'verbose_name': 'Призначене завдання',
                'verbose_name_plural': 'Призначені завдання',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
            preserve_default=False,
        ),
    ]
