# Generated by Django 5.0.4 on 2024-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_homework_options_alter_notes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrouplinks',
            options={'verbose_name': 'Звязок студент-група', 'verbose_name_plural': 'Звязки студент-група'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignments',
            options={'verbose_name': 'Звязок викладач-предмет-група', 'verbose_name_plural': 'Звязки викладач-предмет-група'},
        ),
        migrations.AddField(
            model_name='homework',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='finishdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
