# Generated by Django 5.0.4 on 2024-05-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_studentgrouplinks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.homework', verbose_name='Домашнє завдання')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Чи є правильною')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Фідбек')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.testquestion', verbose_name='Питання')),
            ],
        ),
    ]
