# Generated by Django 5.0.4 on 2024-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_testquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
