# внутрішній_каталог_додатку/management/commands/fill_users.py
#Після цього ви зможете викликати цю команду з терміналу, використовуючи python manage.py fill_db, і вона виконає ваш код

from django.core.management.base import BaseCommand
from django.utils import timezone

#from django.contrib.auth.models import User

from dashboard.models import Task, Subjects, StudentGroups

# Дані для заповнення
task_data = [
    {'subject_id': 1, 'group_id': 1, 'title': 'Послідовності та їх границі', 'description': 'Опис для Послідовностей та їх границь', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Функції та їх неперервність', 'description': 'Опис для Функцій та їх неперервності', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Похідні та їх застосування', 'description': 'Опис для Похідних та їх застосування', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Дослідження функцій за допомогою похідних', 'description': 'Опис для Дослідження функцій за допомогою похідних', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Інтеграли та їх властивості', 'description': 'Опис для Інтегралів та їх властивостей', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Техніки інтегрування', 'description': 'Опис для Технік інтегрування', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Застосування інтегралів', 'description': 'Опис для Застосування інтегралів', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Ряди та їх збіжність', 'description': 'Опис для Рядів та їх збіжності', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Функції декількох змінних', 'description': 'Опис для Функцій декількох змінних', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 1, 'group_id': 1, 'title': 'Кратні інтеграли та їх застосування', 'description': 'Опис для Кратних інтегралів та їх застосування', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 2, 'group_id': 1, 'title': 'Основи теорії ймовірностей', 'description': 'Опис для Основ теорії ймовірностей', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Класична ймовірність та її застосування', 'description': 'Опис для Класичної ймовірності', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Умовні ймовірності та незалежність подій', 'description': 'Опис для Умовних ймовірностей', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Дискретні випадкові величини та їх розподіли', 'description': 'Опис для Дискретних випадкових величин', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Неперервні випадкові величини та їх розподіли', 'description': 'Опис для Неперервних випадкових величин', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Функції випадкових величин та їх розподіли', 'description': 'Опис для Функцій випадкових величин', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Центральна гранична теорема', 'description': 'Опис для Центральної граничної теореми', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Оцінка параметрів та гіпотези', 'description': 'Опис для Оцінки параметрів та гіпотез', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Кореляція та регресійний аналіз', 'description': 'Опис для Кореляції та регресійного аналізу', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 2, 'group_id': 1, 'title': 'Методи математичної статистики', 'description': 'Опис для Методів математичної статистики', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 3, 'group_id': 1, 'title': 'Встановлення Python та основи роботи з інтерпретатором', 'description': 'Опис для Встановлення Python', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Основні типи даних у Python та їх операції', 'description': 'Опис для Основних типів даних у Python', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Управління потоком: умовні конструкції та цикли', 'description': 'Опис для Управління потоком', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Функції в Python: оголошення, аргументи, повернення значень', 'description': 'Опис для Функцій в Python', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Робота зі списками та кортежами', 'description': 'Опис для Роботи зі списками та кортежами', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Робота зі словниками та множинами', 'description': 'Опис для Роботи зі словниками та множинами', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Модулі та пакети: імпорт та організація коду', 'description': 'Опис для Модулів та пакетів', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Обробка винятків та помилок у Python', 'description': 'Опис для Обробки винятків та помилок', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Робота з файлами: читання та запис', 'description': 'Опис для Роботи з файлами', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 3, 'group_id': 1, 'title': 'Введення в об''єктно-орієнтоване програмування в Python', 'description': 'Опис для Об''єктно-орієнтованого програмування', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 4, 'group_id': 1, 'title': 'Введення в синтаксис мови програмування', 'description': 'Опис для Введення в синтаксис мови програмування', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Змінні та типи даних', 'description': 'Опис для Змінні та типи даних', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Умовні конструкції та цикли', 'description': 'Опис для Умовні конструкції та цикли', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Функції та їх використання', 'description': 'Опис для Функції та їх використання', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Масиви та колекції', 'description': 'Опис для Масивів та колекцій', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Основи об''єктно-орієнтованого програмування', 'description': 'Опис для Основи ООП', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Введення в роботу з файлами та потоками даних', 'description': 'Опис для Введення в роботу з файлами та потоками даних', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Основи алгоритмізації', 'description': 'Опис для Основ алгоритмізації', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Основи роботи з базами даних', 'description': 'Опис для Основ роботи з базами даних', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 4, 'group_id': 1, 'title': 'Принципи розробки програмного забезпечення', 'description': 'Опис для Принципів розробки ПЗ', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 5, 'group_id': 1, 'title': 'Основи теорії множин', 'description': 'Опис для Основ теорії множин', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Бінарні відношення та їх властивості', 'description': 'Опис для Бінарних відношень', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Елементи комбінаторики', 'description': 'Опис для Елементів комбінаторики', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Графи та їх застосування', 'description': 'Опис для Графів', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Алгоритми на графах', 'description': 'Опис для Алгоритмів на графах', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Дерева та їх властивості', 'description': 'Опис для Дерев та їх властивостей', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Булеві функції та їх мінімізація', 'description': 'Опис для Булевих функцій', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Теорія ігор', 'description': 'Опис для Теорії ігор', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Математична логіка та методи доведення', 'description': 'Опис для Математичної логіки', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 5, 'group_id': 1, 'title': 'Рекурсивні функції та їх застосування', 'description': 'Опис для Рекурсивних функцій', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 6, 'group_id': 2, 'title': 'Основи мови програмування C#', 'description': 'Опис для Основ мови програмування C#', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Структура програми на C#', 'description': 'Опис для Структури програми на C#', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Типи даних та змінні', 'description': 'Опис для Типів даних та змінних', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Умовні конструкції та цикли', 'description': 'Опис для Умовних конструкцій та циклів', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Масиви та колекції', 'description': 'Опис для Масивів та колекцій', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Робота з рядками', 'description': 'Опис для Роботи з рядками', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Основи об''єктно-орієнтованого програмування', 'description': 'Опис для Основ ООП', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Класи та об''єкти', 'description': 'Опис для Класів та об''єктів', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Наслідування та поліморфізм', 'description': 'Опис для Наслідування та поліморфізму', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 6, 'group_id': 2, 'title': 'Інтерфейси та абстрактні класи', 'description': 'Опис для Інтерфейсів та абстрактних класів', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 7, 'group_id': 2, 'title': 'Основи алгоритмізації', 'description': 'Опис для Основ алгоритмізації', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Структури даних: масиви, списки, стеки, черги', 'description': 'Опис для Структур даних', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Сортування та пошук', 'description': 'Опис для Сортування та пошуку', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Рекурсивні алгоритми', 'description': 'Опис для Рекурсивних алгоритмів', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Дерева та їх застосування', 'description': 'Опис для Дерев та застосування', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Графи та алгоритми на графах', 'description': 'Опис для Графів та алгоритмів', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Хешування та хеш-таблиці', 'description': 'Опис для Хешування та хеш-таблиць', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Алгоритми на рядках', 'description': 'Опис для Алгоритмів на рядках', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Динамічне програмування', 'description': 'Опис для Динамічного програмування', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 7, 'group_id': 2, 'title': 'Алгоритми жадібного програмування', 'description': 'Опис для Алгоритмів жадібного програмування', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 8, 'group_id': 2, 'title': 'Вектори в просторі', 'description': 'Опис для Векторів в просторі', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Лінії та площини', 'description': 'Опис для Ліній та площин', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Відстані та кут між прямими та площинами', 'description': 'Опис для Відстаней та кутів', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Лінійні простори та підпростори', 'description': 'Опис для Лінійних просторів та підпросторів', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Лінійні перетворення', 'description': 'Опис для Лінійних перетворень', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Матриці та їх операції', 'description': 'Опис для Матриць та їх операцій', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Детермінанти та обернені матриці', 'description': 'Опис для Детермінантів та обернених матриць', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Системи лінійних рівнянь', 'description': 'Опис для Систем лінійних рівнянь', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Лінійні функції та їх графіки', 'description': 'Опис для Лінійних функцій та графіків', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 8, 'group_id': 2, 'title': 'Векторні простори та їх властивості', 'description': 'Опис для Векторних просторів та їх властивостей', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 9, 'group_id': 2, 'title': 'Основи схемотехніки', 'description': 'Опис для Основ схемотехніки', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Логічні елементи та їхні властивості', 'description': 'Опис для Логічних елементів', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Комбінаційні логічні схеми', 'description': 'Опис для Комбінаційних логічних схем', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Послідовні логічні схеми', 'description': 'Опис для Послідовних логічних схем', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Лінійні та нелінійні регістри', 'description': 'Опис для Регістрів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Схеми лічильників', 'description': 'Опис для Схем лічильників', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Схеми перетворення коду', 'description': 'Опис для Схем перетворення коду', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Системи операційної пам''яті', 'description': 'Опис для Систем операційної пам''яті', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Проектування мікропроцесорів', 'description': 'Опис для Проектування мікропроцесорів', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 9, 'group_id': 2, 'title': 'Основи архітектури комп''ютерів', 'description': 'Опис для Основ архітектури комп''ютерів', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 10, 'group_id': 2, 'title': 'HTML та CSS: основи розмітки та стилізації', 'description': 'Опис для HTML та CSS', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Використання JavaScript у веб-розробці', 'description': 'Опис для JavaScript', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Робота з DOM: маніпулювання елементами сторінки', 'description': 'Опис для DOM', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Обробка подій та взаємодія з користувачем', 'description': 'Опис для Обробки подій', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Розробка інтерфейсів користувача: використання фреймворків та бібліотек', 'description': 'Опис для Розробки інтерфейсів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Адаптивний дизайн та кросбраузерна сумісність', 'description': 'Опис для Адаптивного дизайну', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Робота з асинхронними запитами та веб-службами', 'description': 'Опис для Асинхронних запитів', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Використання клієнтських бібліотек для взаємодії зі сторонніми сервісами', 'description': 'Опис для Клієнтських бібліотек', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Оптимізація продуктивності та безпеки клієнтської частини', 'description': 'Опис для Оптимізації продуктивності', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 10, 'group_id': 2, 'title': 'Розробка односторінкових додатків (SPA)', 'description': 'Опис для Розробки SPA', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 11, 'group_id': 3, 'title': 'Основи реляційної моделі даних', 'description': 'Опис для Основ реляційної моделі даних', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Мова структурованих запитів SQL', 'description': 'Опис для SQL', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Створення баз даних: структура та обмеження', 'description': 'Опис для Створення баз даних', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Операції з даними: вставка, оновлення, видалення', 'description': 'Опис для Операцій з даними', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Перегляди та індекси в базах даних', 'description': 'Опис для Переглядів та індексів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Транзакції та управління конкурентністю', 'description': 'Опис для Транзакцій', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Нормалізація баз даних: перша, друга, третя та інші нормальні форми', 'description': 'Опис для Нормалізації баз даних', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Функції, тригери та збережені процедури в SQL', 'description': 'Опис для Функцій та тригерів', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Розподілені бази даних та реплікація', 'description': 'Опис для Розподілених баз даних', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 11, 'group_id': 3, 'title': 'Основи адміністрування баз даних: бекапи, відновлення, моніторинг', 'description': 'Опис для Адміністрування баз даних', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 12, 'group_id': 3, 'title': 'Введення в серверну розробку: архітектурні принципи та технології', 'description': 'Опис для Введення в серверну розробку', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Мови програмування для серверної розробки: PHP, Node.js, Python і т.д.', 'description': 'Опис для Мов програмування', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Створення серверних додатків: веб-сервери та маршрутизація', 'description': 'Опис для Створення серверних додатків', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Робота з базами даних на серверному боці: SQL та NoSQL рішення', 'description': 'Опис для Роботи з базами даних', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Створення API для взаємодії з клієнтською частиною', 'description': 'Опис для Створення API', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Автентифікація та авторизація користувачів', 'description': 'Опис для Автентифікації та авторизації', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Обробка запитів: обробка форм, завантаження файлів, обробка AJAX-запитів', 'description': 'Опис для Обробки запитів', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Робота з сесіями та кукісами', 'description': 'Опис для Роботи з сесіями та кукісами', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Інтеграція з іншими сервісами: внутрішні та зовнішні API', 'description': 'Опис для Інтеграції з сервісами', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 12, 'group_id': 3, 'title': 'Оптимізація та моніторинг серверної частини', 'description': 'Опис для Оптимізації та моніторингу', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 13, 'group_id': 3, 'title': 'Введення в Data Science: поняття, завдання, інструменти', 'description': 'Опис для Введення в Data Science', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Збір та підготовка даних для аналізу', 'description': 'Опис для Збору даних', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Експлоративний аналіз даних: візуалізація та статистичний аналіз', 'description': 'Опис для Експлоративного аналізу', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Машинне навчання: основні підходи та алгоритми', 'description': 'Опис для Машинного навчання', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Крос-валідація та оцінка моделей машинного навчання', 'description': 'Опис для Крос-валідації', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Кластерний аналіз та сегментація даних', 'description': 'Опис для Кластерного аналізу', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Завдання класифікації та регресії в Data Science', 'description': 'Опис для Класифікації та регресії', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Обробка текстових даних та аналіз текстів', 'description': 'Опис для Обробки текстових даних', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Основи обробки зображень та комп''ютерного зору', 'description': 'Опис для Обробки зображень', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 13, 'group_id': 3, 'title': 'Впровадження моделей в реальні проекти та робота з великими обсягами даних', 'description': 'Опис для Впровадження моделей', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 14, 'group_id': 3, 'title': 'Введення в React: основні поняття та концепції', 'description': 'Опис для Введення в React', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Створення компонентів та їх використання', 'description': 'Опис для Створення компонентів', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Робота зі станом компонентів', 'description': 'Опис для Роботи зі станом', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Управління подіями та взаємодія між компонентами', 'description': 'Опис для Управління подіями', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Використання життєвого циклу компонентів', 'description': 'Опис для Життєвого циклу компонентів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Маршрутизація та навігація в React додатках', 'description': 'Опис для Маршрутизації та навігації', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Робота з формами та валідація введених даних', 'description': 'Опис для Валідації форм', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Використання сторонніх бібліотек та модулів у React проектах', 'description': 'Опис для Сторонніх бібліотек', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Розробка односторінкових додатків (SPA) за допомогою React', 'description': 'Опис для Розробки SPA', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 14, 'group_id': 3, 'title': 'Тестування та налагодження React додатків', 'description': 'Опис для Тестування React', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 15, 'group_id': 3, 'title': 'Введення в розробку ігор: основні поняття та технології', 'description': 'Опис для Введення в розробку ігор', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Основи геймдизайну та структура гри', 'description': 'Опис для Основ геймдизайну', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Використання графіки та анімації в ігровому дизайні', 'description': 'Опис для Використання графіки', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Механіки гри: керування, фізика, штучний інтелект', 'description': 'Опис для Механік гри', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Створення ігрових об''єктів та їх взаємодія', 'description': 'Опис для Створення об''єктів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Обробка введення користувача: клавіатура, миша, сенсорні екрани', 'description': 'Опис для Обробки введення', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Реалізація музики та звуків у ігровому середовищі', 'description': 'Опис для Реалізації музики', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Тестування та оптимізація ігрових додатків', 'description': 'Опис для Тестування ігор', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Розробка ігор для різних платформ: мобільні пристрої, веб, PC', 'description': 'Опис для Розробки ігор', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 15, 'group_id': 3, 'title': 'Впровадження мережевої гри та багатокористувацькості', 'description': 'Опис для Мережевої гри', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 16, 'group_id': 4, 'title': 'Основні принципи об''єктно-орієнтованого програмування (ООП)', 'description': 'Опис для ООП', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Класи та об''єкти: оголошення, властивості, методи', 'description': 'Опис для Класів та об''єктів', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Наслідування та поліморфізм', 'description': 'Опис для Наслідування та поліморфізму', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Інтерфейси та абстрактні класи', 'description': 'Опис для Інтерфейсів та абстрактних класів', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Шаблони проектування: основні поняття та практичне застосування', 'description': 'Опис для Шаблонів проектування', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Модульність та компонентний підхід у програмуванні', 'description': 'Опис для Модульності та компонентного підходу', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Робота зі збірниками та модулями', 'description': 'Опис для Роботи зі збірниками', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Обробка помилок та винятків у програмах', 'description': 'Опис для Обробки помилок', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Сучасні практики програмування: тестування, рефакторинг, код-рев''ю', 'description': 'Опис для Практик програмування', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 16, 'group_id': 4, 'title': 'Аспекти безпеки та оптимізації у програмуванні', 'description': 'Опис для Аспектів безпеки та оптимізації', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 17, 'group_id': 4, 'title': 'Основи комп’ютерних мереж: поняття, архітектура, типи мереж', 'description': 'Опис для Основ комп’ютерних мереж', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Моделі комп’ютерних мереж: OSI та TCP/IP', 'description': 'Опис для Моделей комп’ютерних мереж', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Протоколи передачі даних: TCP, UDP, IP, ICMP, ARP, DHCP і т.д.', 'description': 'Опис для Протоколів передачі даних', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Локальні мережі: Ethernet, Wi-Fi, Bluetooth', 'description': 'Опис для Локальних мереж', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Безпровідні мережі та їх характеристики', 'description': 'Опис для Безпровідних мереж', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Мережеве обладнання: комутатори, маршрутизатори, маршрутизатори, мости, хаби і т.д.', 'description': 'Опис для Мережевого обладнання', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Мережеве програмування: сокети, клієнт-серверні додатки', 'description': 'Опис для Мережевого програмування', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Віртуальні приватні мережі (VPN) та їх застосування', 'description': 'Опис для VPN', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Безпека мереж: засоби захисту, фірефоли, IDS/IPS системи', 'description': 'Опис для Безпеки мереж', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 17, 'group_id': 4, 'title': 'Управління та моніторинг комп’ютерних мереж', 'description': 'Опис для Управління та моніторингу мереж', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 18, 'group_id': 4, 'title': 'Огляд мобільних платформ: Android, iOS, Windows Mobile', 'description': 'Опис для Огляду мобільних платформ', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Основи мобільного додатку: структура, життєвий цикл, компоненти', 'description': 'Опис для Основ мобільного додатку', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Мови програмування для мобільних додатків: Java/Kotlin для Android, Swift для iOS, C# для Windows Mobile', 'description': 'Опис для Мов програмування', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота з інтерфейсом користувача: розмітка, елементи керування, стилізація', 'description': 'Опис для Роботи з інтерфейсом користувача', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота зі звичайними операціями: обробка подій, взаємодія зі спеціальними функціями пристрою', 'description': 'Опис для Роботи з операціями', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота з мережею: взаємодія з віддаленими сервісами, обробка даних', 'description': 'Опис для Роботи з мережею', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота з базами даних: локальні та віддалені бази даних, синхронізація даних', 'description': 'Опис для Роботи з базами даних', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота з мультимедіа: фото, відео, аудіо', 'description': 'Опис для Роботи з мультимедіа', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Робота з сенсорними пристроями: акселерометр, геолокація, жести', 'description': 'Опис для Роботи з сенсорними пристроями', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 18, 'group_id': 4, 'title': 'Розробка гібридних та крос-платформенних додатків', 'description': 'Опис для Розробки додатків', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 19, 'group_id': 4, 'title': 'Основні поняття та принципи тестування ПЗ', 'description': 'Опис для Основних понять та принципів тестування ПЗ', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Типи тестування: модульне, інтеграційне, системне, приймальне, регресійне та ін.', 'description': 'Опис для Типів тестування', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Методи тестування: чорний ящик, білий ящик, сіре ящикове тестування', 'description': 'Опис для Методів тестування', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Створення тестової документації: плани тестування, тест-кейси, тест-сценарії', 'description': 'Опис для Створення тестової документації', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Автоматизоване тестування: інструменти та практики', 'description': 'Опис для Автоматизованого тестування', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Тестування додаткових якостей ПЗ: навантажувальне, стрес-тестування, безпека, сумісність і т. д.', 'description': 'Опис для Тестування додаткових якостей ПЗ', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Тестування відкритих та закритих систем', 'description': 'Опис для Тестування відкритих та закритих систем', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Методи аналізу дефектів та їх усунення', 'description': 'Опис для Методів аналізу дефектів', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Метрики тестування та їх використання для оцінки якості ПЗ', 'description': 'Опис для Метрик тестування', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 19, 'group_id': 4, 'title': 'Тестування адаптивних, мобільних та веб-додатків', 'description': 'Опис для Тестування адаптивних, мобільних та веб-додатків', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 20, 'group_id': 5, 'title': 'Основні загрози інформаційній безпеці', 'description': 'Опис для Основних загроз інформаційній безпеці', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Принципи та методи криптографії', 'description': 'Опис для Принципів та методів криптографії', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Аутентифікація та авторизація користувачів', 'description': 'Опис для Аутентифікації та авторизації користувачів', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Захист мережевого трафіку: VPN, SSL/TLS, SSH', 'description': 'Опис для Захисту мережевого трафіку', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Захист від вторгнень: файрволи, IPS/IDS системи, HIDS/NIDS', 'description': 'Опис для Захисту від вторгнень', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Захист даних на різних рівнях: шифрування, резервне копіювання, права доступу', 'description': 'Опис для Захисту даних на різних рівнях', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Захист від соціального інжинірингу та фішингу', 'description': 'Опис для Захисту від соціального інжинірингу', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Методи виявлення та аналізу вразливостей систем', 'description': 'Опис для Методів виявлення та аналізу вразливостей систем', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Управління подіями та інцидентами безпеки', 'description': 'Опис для Управління подіями та інцидентами безпеки', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 20, 'group_id': 5, 'title': 'Стандарти та законодавство у сфері інформаційної безпеки', 'description': 'Опис для Стандартів та законодавства у сфері інформаційної безпеки', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 21, 'group_id': 5, 'title': 'Основні концепції та методології управління проєктами', 'description': 'Опис для Основних концепцій та методологій управління проєктами', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Формулювання проектних завдань та постановка цілей', 'description': 'Опис для Формулювання проектних завдань та постановки цілей', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Планування проєкту: розподіл завдань, графіки, ресурси', 'description': 'Опис для Планування проєкту', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Керування бюджетом та фінансами проєкту', 'description': 'Опис для Керування бюджетом та фінансами проєкту', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Створення команди проєкту та її управління', 'description': 'Опис для Створення команди проєкту та управління нею', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Моніторинг та контроль процесу виконання проєкту', 'description': 'Опис для Моніторингу та контролю процесу виконання проєкту', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Управління ризиками та невдачами проєкту', 'description': 'Опис для Управління ризиками та невдачами проєкту', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Залучення зацікавлених сторін та взаємодія з ними', 'description': 'Опис для Залучення зацікавлених сторін та взаємодії з ними', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Оцінка результатів та впровадження змін в процесі виконання проєкту', 'description': 'Опис для Оцінки результатів та впровадження змін', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 21, 'group_id': 5, 'title': 'Аналіз та вдосконалення процесів управління ІТ-проєктами', 'description': 'Опис для Аналізу та вдосконалення процесів управління ІТ-проєктами', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 22, 'group_id': 5, 'title': 'Основи колективної роботи над проєктом', 'description': 'Опис для Основ колективної роботи над проєктом', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Системи контролю версій: Git, SVN, Mercurial', 'description': 'Опис для Систем контролю версій', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Інструменти спільної розробки коду: GitHub, GitLab, Bitbucket', 'description': 'Опис для Інструментів спільної розробки коду', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Системи управління завданнями та проектами: Jira, Trello, Asana', 'description': 'Опис для Систем управління завданнями', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Спільне документування проєктів: Google Docs, Confluence, Wiki', 'description': 'Опис для Спільного документування проєктів', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Колаборативне планування та спільне прийняття рішень', 'description': 'Опис для Колаборативного планування', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Відслідковування змін та аналіз результів колективної роботи', 'description': 'Опис для Відслідковування змін', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Використання комунікаційних інструментів у роботі над проєктом', 'description': 'Опис для Використання комунікаційних інструментів', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Керування конфліктами та спірними питаннями у групі', 'description': 'Опис для Керування конфліктами', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 22, 'group_id': 5, 'title': 'Організація ефективних онлайн-зборів та відстеження прогресу роботи', 'description': 'Опис для Організації ефективних онлайн-зборів', 'deadline': timezone.now() + timezone.timedelta(days=75)},

    {'subject_id': 23, 'group_id': 5, 'title': 'Основи штучного інтелекту та машинного навчання', 'description': 'Опис для Основ штучного інтелекту та машинного навчання', 'deadline': timezone.now() + timezone.timedelta(days=30)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Методи класифікації та регресії', 'description': 'Опис для Методів класифікації та регресії', 'deadline': timezone.now() + timezone.timedelta(days=35)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Кластерний аналіз та сегментація даних', 'description': 'Опис для Кластерного аналізу та сегментації даних', 'deadline': timezone.now() + timezone.timedelta(days=40)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Методи виявлення аномалій та асоціативного аналізу', 'description': 'Опис для Методів виявлення аномалій та асоціативного аналізу', 'deadline': timezone.now() + timezone.timedelta(days=45)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Нейронні мережі та їх застосування', 'description': 'Опис для Нейронних мереж та їх застосування', 'deadline': timezone.now() + timezone.timedelta(days=50)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Глибинне навчання та зображення', 'description': 'Опис для Глибинного навчання та зображення', 'deadline': timezone.now() + timezone.timedelta(days=55)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Обробка природної мови та генерація тексту', 'description': 'Опис для Обробки природної мови та генерації тексту', 'deadline': timezone.now() + timezone.timedelta(days=60)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Рекомендаційні системи: основні підходи та методи', 'description': 'Опис для Рекомендаційних систем', 'deadline': timezone.now() + timezone.timedelta(days=65)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Системи розпізнавання образів та обробка відео', 'description': 'Опис для Систем розпізнавання образів та обробки відео', 'deadline': timezone.now() + timezone.timedelta(days=70)},
    {'subject_id': 23, 'group_id': 5, 'title': 'Прикладні застосування інтелектуальних інформаційних систем', 'description': 'Опис для Прикладних застосувань', 'deadline': timezone.now() + timezone.timedelta(days=75)}
]


class Command(BaseCommand):
    help = 'Заповнення таблиці Tasks за допомогою Django ORM'  #python manage.py fill_db --help - виклик допомоги

    def handle(self, *args, **kwargs):
        time = timezone.now().strftime('%X')
        self.stdout.write("It's now %s" % time)

        # Заповнення таблиці
        for data in task_data:
            t = Task.objects.create(
                subject_id=data['subject_id'],
                group_id=data['group_id'],
                title=data['title'],
                description=data['description'],
                deadline=data['deadline'])
            t.save()


